# 👉 We don't want to make our wifi password so create a settings.toml file with the correct creds
WIFI_SSID="HUAWEI-DCE4-5G"
WIFI_PASSWORD="PastePasswordHere"
API_ENDPOINT="https://api.npoint.io/33e561d387e334b1184d"
HELMET_ID="helm1"